### ISSUE TITLE
about the table 1

### ISSUE THREAD

**Issue by Betty-J** [tinyalpha/BPR#11]
Hi thanks for your work, a little question about table 1, you said "∞ means all error pixels are corrected. ", I can't understand "all error pixels are corrected" but you get AP 70.4, why? how to definition "error pixels for boundaries"， could you explain more, thanks a lot!

**Comment by chenhang98** [comment]
We first match DT and GT masks according to IoU, and then replace pixels within a certain distance (denoted by d) around the boundary of DT with the value (0 or 1) corresponding to GT.
In this process, missed instances and classification errors are not corrected. So even if d is infinity, AP is not 100.
