### ISSUE TITLE
mmcv error

### ISSUE THREAD

**Issue by ellesecotterill** [tinyalpha/BPR#13]
Hi,

I'm trying to run
 `sh tools/inference.sh`
but getting the error `ModuleNotFoundError: No module named 'mmcv._ext'`

Are there specific versions of mmdet and mmcv you would suggest using? The versions I am using are 
`mmdet 2.6.0`
`mmcv 1.1.5`

Thanks,
Ellese

**Comment by chenhang98** [comment]
You need to install `mmcv-full` instead of `mmcv`, because the latter does not contain CUDA operators. Please refer to https://mmcv.readthedocs.io/en/latest/get_started/installation.html for details.

My versions are
```
mmcv-full                 1.1.6                    pypi_0    pypi
mmdet                     1.2.0+0f33c08             dev_0    <develop>
mmsegmentation            0.7.0                     dev_0    <develop>
```

**Comment by fathyshalaby** [comment]
which pytorch and cuda version did you use as it seems that even 1.2.0 actually very outdated is and doesn't work with newer gpus (3090).

**Comment by chenhang98** [comment]
@fathyshalaby Our pytorch and torchvision versions are 1.4.0 and 0.5.0 respectively, and the CUDA version is 10.0
