### ISSUE TITLE
Is Tutorial Material still useful in the current version？

### ISSUE THREAD

**Issue by ai1urus** [tinyalpha/BPR#14]
Thanks for the amazing work!

I am trying to run inference in my own datasets. 

I found some tutorials in **./demo** and **./docs**, are these materials still useful in the current version?

**Comment by chenhang98** [comment]
No, these files are from [mmsegmentation](https://github.com/open-mmlab/mmsegmentation) without modification.
It is recommended that you first convert the dataset to COCO or Cityscape format, and then use [inference_coco.sh](https://github.com/tinyalpha/BPR/blob/main/tools/inference_coco.sh) or [inference.sh](https://github.com/tinyalpha/BPR/blob/main/tools/inference.sh) for inference.

**Comment by ai1urus** [comment]
> No, these files are from [mmsegmentation](https://github.com/open-mmlab/mmsegmentation) without modification.
> It is recommended that you first convert the dataset to COCO or Cityscape format, and then use [inference_coco.sh](https://github.com/tinyalpha/BPR/blob/main/tools/inference_coco.sh) or [inference.sh](https://github.com/tinyalpha/BPR/blob/main/tools/inference.sh) for inference.

Got it. Thank you!
