### ISSUE TITLE
visualization of cityscapes segmentation result?

### ISSUE THREAD

**Issue by yangshunDragon** [tinyalpha/BPR#15]
Nice project! Thanks for opening source.
Could you please share the code of visualization of citycapes segmentation results(the visualization output you display when compare MASK RCNN with BPR)?  
Thanks in adanvance!

**Comment by chenhang98** [comment]
Please refer to  https://cloud.tsinghua.edu.cn/f/08836b790f4648e7beca/?dl=1
Note that the rectangular boxes in the figures were drawn manually, not by code.

**Comment by yangshunDragon** [comment]
@tinyalpha  Got it. Thanks very much!

**Comment by apanand14** [comment]
Thank you so much! I will look into it!
