### ISSUE TITLE
KeyError: 'ann_info'

### ISSUE THREAD

**Issue by wanxinjun** [tinyalpha/BPR#16]
Thanks for your error report and we appreciate it a lot.

1. What command or script did you run?
python demo/image_demo.py demo/demo.png     configs/bpr/hrnet48_256.py  checkpoints/hrnet48_256-cbf4922c.pth

2. Please run `python mmseg/utils/collect_env.py` to collect necessary environment infomation and paste it here.
TorchVision: 0.6.0a0+35d732a
OpenCV: 4.5.3
MMCV: 1.2.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMSegmentation: 0.7.0+e3674fe

**Error traceback**

If applicable, paste the error trackback here.

Traceback (most recent call last):
  File "demo/image_demo.py", line 29, in <module>
    main()
  File "demo/image_demo.py", line 23, in main
    result = inference_segmentor(model, args.img)
  File "/home/wanxinjun/anaconda3/envs/BPR/lib/python3.7/site-packages/mmsegmentation-0.7.0-py3.7.egg/mmseg/apis/inference.py", line 86, in inference_segmentor
    data = test_pipeline(data)
  File "/home/wanxinjun/anaconda3/envs/BPR/lib/python3.7/site-packages/mmsegmentation-0.7.0-py3.7.egg/mmseg/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/wanxinjun/anaconda3/envs/BPR/lib/python3.7/site-packages/mmsegmentation-0.7.0-py3.7.egg/mmseg/datasets/pipelines/loading.py", line 125, in __call__
    filename = results['ann_info']['seg_map']
KeyError: 'ann_info'

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by wanxinjun** [comment]
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3: GeForce GTX 1080
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 9.0, V9.0.176
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
PyTorch: 1.5.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+35d732a
OpenCV: 4.5.3
MMCV: 1.2.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMSegmentation: 0.7.0+e3674fe

**Comment by chenhang98** [comment]
The script `demo/image_demo.py` is from mmsegmentation. Our code currently does not support inference on a single image.

**Comment by chenhang98** [comment]
I will delete these scripts since they are misleading.
