### ISSUE TITLE
Do you have the code to convert labelme to the format required by this algorithm?

### ISSUE THREAD

**Issue by Ocean-ZHY** [tinyalpha/BPR#17]
I can’t understand the data set conversion you mentioned in Training. This has troubled me for a long time. Do you have any relevant code? What does coarse_json_train_filtered in tools/prepare_dataset.sh mean? thank you

**Comment by chenhang98** [comment]
Sorry for the late reply. 
You can first convert to COCO format, and then follow https://github.com/tinyalpha/BPR#on-other-datasets .
When constructing the training set, we do not include the bounding boxes whose IoU with ground truth is less than 0.5.  These boxes are many and are harmful to performance. So we filter it first and save the result in `coarse_json_train_filtered`.
