### ISSUE TITLE
could you tell me how to prepare patches dataset? such as the json format, thanks

### ISSUE THREAD

**Issue by chenxin-x** [tinyalpha/BPR#18]

**Comment by chenhang98** [comment]
Sorry for the late reply. I have updated the README, you can refer to https://github.com/tinyalpha/BPR#on-other-datasets

**Comment by chenxin-x** [comment]
Thank you very much for your reply.&nbsp;I have successfully run this code.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tinyalpha/BPR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tinyalpha/BPR] could you tell me how to prepare patches dataset? such as the json format, thanks (#18)





 
Sorry for the late reply. I have updated the README, you can refer to https://github.com/tinyalpha/BPR#on-other-datasets
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
