### ISSUE TITLE
Run BPR using COCO datset and json files

### ISSUE THREAD

**Issue by apanand14** [tinyalpha/BPR#19]
Hey, I'm new to this. how can I run your code using COCO dataset and respective json files?

Thank you for your help and time!

**Comment by chenhang98** [comment]
You can use [tools/inference_coco.sh](https://github.com/tinyalpha/BPR/blob/main/tools/inference_coco.sh) to inference on COCO dataset. Pre-trained model is provided [here](https://cloud.tsinghua.edu.cn/f/342fae1311b748a8b396/?dl=1).
For more details, please refer to https://github.com/tinyalpha/BPR#on-other-datasets

**Comment by apanand14** [comment]
Thank you for answer. Btw I'm not able to open the link which you have sent for more details. I would like to train on my custom datatset which in COCO format only. Is it possible to train and do inference with your scripts for COCO format custom dataset? Also Please let me know if you have any documentation for how to run on your codes for custom COCO datasets and reproduce the results. Thank you in advance.

**Comment by chenhang98** [comment]
I have updated the README, please refer to https://github.com/tinyalpha/BPR#on-other-datasets

**Comment by apanand14** [comment]
Thank you so much for the detailed information. It will surely help me. Thanks once again! Just one question, Will it work on windows as well, right?

**Comment by chenhang98** [comment]
We only tested on Linux. I think the bash scripts cannot run on windows...

**Comment by tinyalpha** [comment]
We only tested on Linux. I think the bash scripts cannot run on windows...

**Comment by apanand14** [comment]
Okay. I will try to run bash script on windows if possible using some method. But Do you have any idea to run your codes without using bash script on windows? I mean first I run filter.py, then split_patches.py. I will get the dataset saved in maskrcnn_r50/patches. After that I run train.py to train refinement network. This way way it should work, right?

**Comment by chenhang98** [comment]
Yes, I think it should work.

**Comment by apanand14** [comment]
Okay. thank you for your answer. I will let you know if this works.

**Comment by apanand14** [comment]
Hello @tinyalpha,
For the training you asked me to run following command:
**IOU_THRESH=0.15 \
sh tools/prepare_dataset_coco.sh \
  mask_rcnn_r50.train.segm.json \
  mask_rcnn_r50.val.segm.json \
  maskrcnn_r50 \
  70000**

But I'm a bit confused about the format of the both json files (mask_rcnn_r50.train.segm.json and mask_rcnn_r50.val.segm.json). What exactly these json files contain? It would be helpful if you explain in detail about it. Thank you in advance.

**Comment by chenhang98** [comment]
They meet the results format of the COCO dataset, as described in https://cocodataset.org/#format-results
Here is our example, https://cloud.tsinghua.edu.cn/f/d86b4a4e67544dc494ae/?dl=1

**Comment by apanand14** [comment]
Thank you for sharing sample! but how should I get this json files? I mean is it a result of any segmentation or what? It would be better you explain how will I get these json files? Thank you!
I have following structure on my PC:
**BPR
├── data
│   ├── coco
│   │   ├── annotations
│   │   ├── train2017
│   │   ├── val2017
│   │   ├── test2017**

But how will I get mask_rcnn_r50.train.segm.json and mask_rcnn_r50.val.segm.json?? After running preapre_dataset_coco.sh ?? or both are the input files to make run prepare_dataset_coco.sh??

**Comment by chenhang98** [comment]
Note that our BPR is a post-processing algorithm. If you have any instance segmentation results, after running BPR, you can get a better one. For training BPR, some coarse instance segmentation results should be provided as input. In our experiments, we use the results from Mask R-CNN with ResNet-50 backbone. It was generated using [mmdetecion](https://github.com/open-mmlab/mmdetection).

**Comment by apanand14** [comment]
Okay.  i got it. I also use customized mask rcnn with resnet 50 backbone using mmdetection. But I didn't saved results in json files. Do I have to store them? or did you also store results from mmdetection in these mask_rcnn_r50_train.segm.json and mask_rcnn_r50_val.segm.json??

**Comment by chenhang98** [comment]
Yes, you need to run Mask R-CNN on your training and test set and save the results in json format.

**Comment by apanand14** [comment]
okay. And It will save results in particular format which you showed me? And one more question what is counts in that json file under the segmentation key?

**Comment by chenhang98** [comment]
Yes. It is the run-length encoding of the instance mask.

**Comment by apanand14** [comment]
Okay. thank you for the all information. I will ask you if I get any error or need any further help.

**Comment by apanand14** [comment]
Hello @tinyalpha ,
As you know i'm running on windows and I'm running files step by step. First I'm running filter.py and I'm getting this error. Can you look into it and help me out? Thank you in advance.
multiprocessing.pool.RemoteTraceback:

Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\BPR\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\BPR\BPR\tools\filter.py", line 22, in max_iou
    maskdt = coco.annToMask(inst)
**AttributeError: 'NoneType' object has no attribute 'annToMask'**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools\filter.py", line 65, in <module>
    Fire(main)
  File "C:\Users\anaconda3\envs\temp_mask\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\anaconda3\envs\temp_mask\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "C:\Users\anaconda3\envs\temp_mask\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "tools\filter.py", line 59, in main
    dt_filtered = filter_iou(dt, thresh)
  File "tools\filter.py", line 40, in filter_iou
    for iou, bbox in p.imap(max_iou, bboxs):
  File "C:\Users\anaconda3\envs\temp_mask\lib\multiprocessing\pool.py", line 748, in next
    raise value

**AttributeError: 'NoneType' object has no attribute 'annToMask'**

**Comment by apanand14** [comment]
Hello @tinyalpha , I have successfully run training and evaluation. One thing I would like to ask that how can I save visualization of inference images instead of json file?

**Comment by chenhang98** [comment]
You can directly visualize the json results, these codes might be helpful for you. #15

**Comment by apanand14** [comment]
Thank you for sharing notebook. I finally able to visualize segmentation results after so many difficulties in preparing dataset, training, inference and merging patches. Thanks alot for helping me out at every stage!
