### ISSUE TITLE
Is the training code and script available now?

### ISSUE THREAD

**Issue by cnnAndBn** [tinyalpha/BPR#2]
hi:
  after reading your paper ,I want to have a try, in the introduction part, only inference and pretrained model are introduced , may I ask is the training code available now? in the config directory, I see the config file for bpr.

**Comment by chenhang98** [comment]
Yes, training code and COCO model are also available, but please wait a moment, I will make it soon.

**Comment by cnnAndBn** [comment]
hi, as for the installation, mmseg/ dir not found. and where is the implementation of EncoderDecoderRefine and RefineDataset,I not found.

**Comment by cnnAndBn** [comment]
I try to clone your code by git clone --recursive https://github.com/tinyalpha/BPR.git @tinyalpha
