### ISSUE TITLE
Hello, author, why is the training time so long, even several days? But there are only a few hundred pictures in my dataset. Do you have a solution?

### ISSUE THREAD

**Issue by weijinmeng** [tinyalpha/BPR#23]
Hello, author, why is the training time so long, even several days? But there are only a few hundred pictures in my dataset. Do you have a solution?

**Comment by chenhang98** [comment]
You can check whether it is because there are too many instances in the coarse segmentation result. It takes about 10 hours for training on 4x 2080Ti GPUs on the cityscapes dataset (2000+ images), for your reference.

**Comment by weijinmeng** [comment]
Thank you for your reply. My&nbsp;coarse segmentation contains many&nbsp;instances, which may cause the slow training.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tinyalpha/BPR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月1日(星期一) 晚上8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tinyalpha/BPR] Hello, author, why is the training time so long, even several days? But there are only a few hundred pictures in my dataset. Do you have a solution? (Issue #23)





 
You can check whether it is because there are too many instances in the coarse segmentation result. It takes about 10 hours for training on 4x 2080Ti GPUs on the cityscapes dataset (2000+ images), for your reference.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weijinmeng** [comment]
Dear author, I have the following problems in the process of inference.&nbsp; I can't find the hrnet18s_coco-c172955f.pth file. And, don't generate mask_rcnn_r50.val.refined.json/refined.pkl file. ‍
subprocess.CalledProcessError: Command '['/icislab/volume4/wjm/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/test_float.py', '--local_rank=3',&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 'configs/bpr/hrnet18s_128.py', 'hrnet18s_coco-c172955f.pth', '--launcher', 'pytorch', '--out', 'mask_rcnn_r50.val.refined.json/refined.pkl']' returned&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; non-zero exit status 1.‍


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "tinyalpha/BPR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月1日(星期一) 晚上8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tinyalpha/BPR] Hello, author, why is the training time so long, even several days? But there are only a few hundred pictures in my dataset. Do you have a solution? (Issue #23)





 
You can check whether it is because there are too many instances in the coarse segmentation result. It takes about 10 hours for training on 4x 2080Ti GPUs on the cityscapes dataset (2000+ images), for your reference.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenhang98** [comment]
You can find the pre-trained model [here](https://github.com/tinyalpha/BPR#models).

**Comment by weijinmeng** [comment]
thank you for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tinyalpha/BPR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 晚上8:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tinyalpha/BPR] Hello, author, why is the training time so long, even several days? But there are only a few hundred pictures in my dataset. Do you have a solution? (Issue #23)





 
You can find the pre-trained model here.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weijinmeng** [comment]
I'm sorry to disturb you many times! I apply it to a COCO like dataset. After the training, the following errors occurred in the inference stage.&nbsp;&nbsp;I look forward to your reply, which is very important to me. thank you!!


Traceback (most recent call last):
&nbsp; File "./tools/test_float.py", line 148, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "./tools/test_float.py", line 117, in main
&nbsp; &nbsp; checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
&nbsp; File "/icislab/volume4/wjm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 247, in load_checkpoint
&nbsp; &nbsp; checkpoint = _load_checkpoint(filename, map_location)
&nbsp; File "/icislab/volume4/wjm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 222, in _load_checkpoint
&nbsp; &nbsp; raise IOError(f'{filename} is not a checkpoint file')
OSError: hrnet18s_coco-c172955f.pth is not a checkpoint file



loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
Traceback (most recent call last):
&nbsp; File "./tools/merge_patches.py", line 104, in <module&gt;
&nbsp; &nbsp; start()
&nbsp; File "./tools/merge_patches.py", line 63, in start
&nbsp; &nbsp; with open(args.res_pkl, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'mask_rcnn_r50.val.refined.json/refined.pkl'



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tinyalpha/BPR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 晚上8:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tinyalpha/BPR] Hello, author, why is the training time so long, even several days? But there are only a few hundred pictures in my dataset. Do you have a solution? (Issue #23)





 
You can find the pre-trained model here.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenhang98** [comment]
You can check whether the file is crroupted during download. The md5sum should be `af557618d1f1b2e861e79d9d01e2f180`.

**Comment by SchernHe** [comment]
I get the same error. Any news on the issue? Moreover, can somebody explain to me why I need the ground truth for the refinement?

**Comment by weijinmeng** [comment]
I tried to train with a single GPU, and the training time was reduced to 10 hours.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tinyalpha/BPR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 凌晨0:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tinyalpha/BPR] Hello, author, why is the training time so long, even several days? But there are only a few hundred pictures in my dataset. Do you have a solution? (Issue #23)





 
I get the same error. Any news on the issue? Moreover, can somebody explain to me why I need the ground truth for the refinement?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lavenda-zhou** [comment]
Hello, author. I have the following problems in the process of inference. 
reassemble ...
+ python ./tools/merge_patches.py ms_rcnn_r50.val.segm.json data/car-coco/annotations/instances_val2017.json ms_rcnn_r40.val.refined.json/refined.pkl ms_rcnn_r40.val.refined.json/patches/detail_dir/val ms_rcnn_r40.val.refined.json/refined.json
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
  0%|                                                  | 0/137 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/mint/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "./tools/merge_patches.py", line 38, in run_inst
    patch_mask = results[pid]
KeyError: 16
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./tools/merge_patches.py", line 110, in <module>
    start()
  File "./tools/merge_patches.py", line 80, in start
    for r in p.imap_unordered(run_inst, enumerate(dt)):
  File "/home/mint/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
KeyError: 16
I look forward to your reply, which is very important to me. thank you!
