### ISSUE TITLE
What exactly are the contents inside the segmentation.json file used in the inference? 

### ISSUE THREAD

**Issue by myDSMLProjects** [tinyalpha/BPR#26]
I can see image_id, bbox, score, category id etcc...what are those things under the key segmentation? what is size and count? Can you kindly give a clarification?

**Comment by chenhang98** [comment]
If you mean the coarse instance segmentation results, e.g. `mask_rcnn_r50.val.segm.json` in the [demo commands](https://github.com/tinyalpha/BPR#inference-1), the contents are COCO style results.
The things under the key segmentation (i.e. size and count) represent the binary instance mask using [RLE](https://en.wikipedia.org/wiki/Run-length_encoding).
It is the standard format of instance segmentation in [COCO dataset](https://cocodataset.org/#format-data).
You can find detailed instructions [here](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/mask.py).
