### ISSUE TITLE
Degenerate results after using BPR, no clues why

### ISSUE THREAD

**Issue by liuzhy71** [tinyalpha/BPR#30]
Hello,

Thank you for the awesome work on post segmetation refinement! 

I tried to apply BPR to my own segmentation dataset. However,  the results I got are worse than the original segmentation results. 

Currently I have no clues why this happens. In the training phase, I have got almost 99% precision and 98% IOU on the validation set. But after I assembled the patches, I found that original mask is corrupted by the patch results. 
![a8_t0_p0_rgb_0_coarse](https://user-images.githubusercontent.com/16524611/167880927-dd1c85b9-e759-4747-8ff3-9773044dadd7.png)

ori

![a8_t0_p0_rgb_0_coarse](https://user-images.githubusercontent.com/16524611/167881732-37227144-90ac-42c5-ba90-dee2296b8261.png)

**Comment by chenhang98** [comment]
This seems strange, you can check if there is something wrong with the setup at inference time.
Here are our validation set statistics on cityscapes and COCO for your reference:
- cityscapes: Iter(val) [160000]	mIoU: 0.7875, mAcc: 0.8903, aAcc: 0.8913
- coco: Iter(val) [160000]	mIoU: 0.7396, mAcc: 0.8599, aAcc: 0.8657

**Comment by liuzhy71** [comment]
Thank you, I'll keep on debugging.
