### ISSUE TITLE
 Getting AP values for each category

### ISSUE THREAD

**Issue by lavenda-zhou** [tinyalpha/BPR#37]
Hello, author. How do I get AP values for each category？I have four different types of vehicles in my dataset and want to know the AP value of each.
I look forward to your reply, which is very important to me. thank you!

**Comment by chenhang98** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/blob/f8bbba2fe777dd882a8da20625be858a98436703/mmdet/datasets/coco.py#L540

**Comment by lavenda-zhou** [comment]
Thank you for your reply. I have solved this problem. Now I find that the patch size is 64*64. Your paper shows that the best input size is 256*256. Where can I change this parameter?  Thank you for your answering.

**Comment by chenhang98** [comment]
The `patch size` and `input size` are not necessarily equal in our work. Simply put, we extract several 64x64 patches and resize them to 256x256 (upsample 4x) before inputting them to HRNet. We use this setting in both the code and the paper.
