### ISSUE TITLE
 Probem about the patch size and the input size of the refinement network.

### ISSUE THREAD

**Issue by lavenda-zhou** [tinyalpha/BPR#39]
Hello, anthor. I have the probem about the patch size and the input size of the refinement network. When I used the small model Hrnet18s_128.py, I found that the input size is 128*128, not 256*256. The output size is 32*32(downsample 4 times). The patch size is 64*64 as the first step has extracted. How can these 32*32 refined patches be reassembled into the original images? The 32*32 output patches do not match the 64*64 input patches. Thank you for your answer in advance.

**Comment by chenhang98** [comment]
(1) Yes, the input patches are resized to 128x128 for `Hrnet18s_128.py` and 256x256 for `hrnet48_256.py`;
(2) The refined patches will be rescaled to their original shape (i.e. 64x64) before saving and reassembling. You can check this line for details: https://github.com/tinyalpha/BPR/blob/a6158280db11b329a264ee5f20818bfc87b73f3a/mmseg/models/segmentors/encoder_decoder.py#L214
