### ISSUE TITLE
Details about the file structure

### ISSUE THREAD

**Issue by YeolJ00** [tinyalpha/BPR#4]
It is unclear what the directory is suppose to contain in the README document.

Suppose you have some instance segmentation results of Cityscapes dataset, as the following format:

maskrcnn_val
- frankfurt_000001_064130_leftImg8bit_pred.txt
- frankfurt_000001_064305_leftImg8bit_0_person.png
- frankfurt_000001_064305_leftImg8bit_10_motorcycle.png
- ...

what is the .txt file suppose to contain?

**Comment by chenhang98** [comment]
Same with the standard format required by the [cityscape script ](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/evaluation/evalInstanceLevelSemanticLabeling.py), e.g.
```
frankfurt_000000_000294_leftImg8bit_0_person.png 24 0.9990299940109253
frankfurt_000000_000294_leftImg8bit_1_person.png 24 0.9810258746147156
frankfurt_000000_000294_leftImg8bit_2_person.png 24 0.3322693705558777
....
```
If you are using mmdetection, the output format meets the requirements automatically
