### ISSUE TITLE
Can this be updated to be used with mmcv 1.7?

### ISSUE THREAD

**Issue by Rifahaziz** [tinyalpha/BPR#40]
Hi, thank you for the amazing work! I was very curious to use this method as a post-processing on a segmentation task. However, it looks like it is highly dependent on mmcv<=1.2.0 which requires CUDA 10.1. I am using RTX 3080 on windows which is incompatible with CUDA<11. So I am not being able to use mmcv 1.2. When I use mmcv 1.7, it shows an error that mmcv<=1.2 or >=1.1.4 is required. I was curious to know whether you would update this repo anytime soon to be used with mmcv 1.7 and CUDA 11. It would be of great help. Thank you!

**Comment by chenhang98** [comment]
Thank you for your interest. We currently have no plans to update. Our code is based on `mmsegmentation` with minor modifications. Maybe you can try to migrate these changes to the new `mmsegmentation` framework. Our modifications are limited to the following files:

- mmseg/models/backbones/resnet_refine.py
- mmseg/models/segmentors/encoder_decoder_refine.py
- mmseg/datasets/refine.py
- mmseg/datasets/pipelines/loading.py

I hope this information is helpful to you.

**Comment by Rifahaziz** [comment]
Hi, thank you for your reply. I was able to use this method at inference on CUDA 11 with mmcv 1.7.1! Even though there was a restriction to use it with mmcv>=1.14 or <=1.2.0, it still works fine with version 1.7.1 when this restriction is removed.

**Comment by chenhang98** [comment]
Close as the issue has been resolved. Feel free to re-open.
