### ISSUE TITLE
How to calculate FPS of processing pictures?

### ISSUE THREAD

**Issue by lavenda-zhou** [tinyalpha/BPR#41]
Hello，anthor. I want to compare the speed of testing pictures before and after adding the boundary improvement  module by  FPS. I wonder how to calculate.

**Comment by chenhang98** [comment]
You can obtain the time for BPR to process a single image by timing the following for loop:

https://github.com/tinyalpha/BPR/blob/d4a56a20d06abda154e66eea15179766e6af3671/demo/inference_img.py#L230-L241
