### ISSUE TITLE
Error in the process of inference

### ISSUE THREAD

**Issue by pythonyyds-byte** [tinyalpha/BPR#48]
ModuleNotFoundError: No module named 'mmdet.ops'
AssertionError: MMCV==1.3.5 is used but incompatible. Please install mmcv>=[1, 1, 4], <=[1, 2, 0].
FileNotFoundError: [Errno 2] No such file or directory: 'mask_rcnn_r50.val.refined.json/refined.pkl'

In the process of reasoning, the above three errors occurred in turn. I suspected that the mmcv-full I used was incompatible with mmdet and mmseg. The following picture is the version of the package I installed. I hope you can explain how to solve this problem.

![微信图片_20230909101358](https://github.com/chenhang98/BPR/assets/103372480/06c58a68-b9d8-4fd5-8df6-688ef7eb8312)

**Comment by chenhang98** [comment]
Hi, you can try decreasing the version of mmcv. The version we used for testing was 1.1.6.

**Comment by pythonyyds-byte** [comment]
Thank you very much, I have fixed the above error with an updated version. However, when I used BPR to refine the coco validation set, the overall runtime exceeded expectations. Is this normal?




Thank you very much, I have fixed the above error with an updated version. However, when I used BPR to refine the coco validation set, the overall runtime exceeded expectations. Is this normal?

Mr.Right
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenhang98/BPR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月11日(星期一) 晚上7:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenhang98/BPR] Error in the process of inference (Issue #48)





 
Hi, you can try decreasing the version of mmcv. The version we used for testing was 1.1.6.

**Comment by chenhang98** [comment]
Yes, running the entire pipeline of BPR on the COCO validation set might take several hours since there are many instances.
