### ISSUE TITLE
about"Prepare patches dataset "

### ISSUE THREAD

**Issue by xinzi2018** [tinyalpha/BPR#7]
maskrcnn_train
- aachen_000000_000019_leftImg8bit_pred.txt
- aachen_000001_000019_leftImg8bit_0_person.png
- aachen_000001_000019_leftImg8bit_10_car.png
- ...

maskrcnn_val
- frankfurt_000001_064130_leftImg8bit_pred.txt
- frankfurt_000001_064305_leftImg8bit_0_person.png
- frankfurt_000001_064305_leftImg8bit_10_motorcycle.png
- ...

How can we get these files?

**Comment by Dinghow** [comment]
I've the same question

**Comment by chenhang98** [comment]
These files are available on https://cloud.tsinghua.edu.cn/d/0ef61308bafa46a49799/
We generated them using https://github.com/open-mmlab/mmdetection/tree/master/configs/cityscapes
